service:
  name: mcsrv-mgr

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"


functions:
  hello:
    handler: handler.hello
    environment: ${file(./secret.yml):environment}
    events: 
      - http:
          method: get
          path: /
          integration: lambda
  get-info:
    handler: get_info.get
    environment: ${file(./secret.yml):environment}
    events:
      - http:
          method: get
          path: /server
          integration: lambda
  update:
    handler: handler.update
    environment: ${file(./secret.yml):environment}
    events:
      - schedule:
        rate: rate(5 minutes)
        enabled: false

resources:
  Resources:
    StatusTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: status_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: status_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: mcsrv-mgr-status
